#!/usr/bin/ruby

require 'byebug'
require 'informer'

terms = ARGV

search_results = Informer.search(terms)

search_results.each do |term, filepaths|
  system("emacsclient -c #{filepaths[:org_filepath]}")
end


